language: c
script:
- bash .travis-build.sh
matrix:
  include:
  - os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - gcc-arm-none-eabi
          - libnewlib-arm-none-eabi
          - dfu-util
    compiler: arm-none-eabi-gcc
    env: OSTYPE=firmware
  - os: linux
    dist: xenial
    compiler: gcc
  - os: osx
    compiler: clang
  - os: linux
    dist: xenial
    compiler: gcc
    env: OSTYPE=msys host_alias=i686-w64-mingw32
deploy:
  provider: releases
  api_key:
    secure: atYC7VgxaZX0BPQsuLxWmxgj6I5ggMUbKHVIBjOAbUZ/IeB4i28/2Ka6nVK7K5ekxIi00m1o5noPp7x4wioHfbBLVGjJVdoopTUbYhZYTZH4HG74v973AQc4y2dMUHOWsBhoud8vZ/RQimXoemQf+GfHZzeHB4tAmfaZdjoYECC4nTSGcOaMCcskFiF2YMdYbgejs1FSYVw1aO8l/FYYmgrCMfz4BeOL9CaSHvuBYMV0MOHqW3urSnD0Nzh9mvugbgLBYh9WTdxsFZKxlgrhM2G8s4+YwRBzWGGXths4CRn0DZsdSYkXlCgi6ZAbybEwkmLT762U+b40FgZLCcNcwIfQ4AGqofoMpIjNAbGy6IaH9krm+5/MZTe3bCnGjQbaDJaOGBxOqnrDGVoWncb78Csh9sdB9dxmopqjguyifL+/bI26ifQ6Qqydgb3/TAHm+p2vPhar5yPf7hUuAgYfaOgI5PO/hh4HU7ss9IeTEhN3gyif+nbKy9YnLrm4Y5X3uwojbeTyezoThoJDRkTRDBJOTo15bPG/xQG8dADXfvqjc1xbaOve/OF2ouIdWbxheQ5JG+RS3fyoizO5GGyVEA5FKQNtZ/2vpm3I+C09q/jqW6V4GMzY4BoLmpTVjOL1xbScPru2Oip8XAujBfU4a0ct1kXiO4xJwIBv5rv3UWU=
  skip_cleanup: true
  file_glob: true
  file: $(pwd)/build/*.zip
  on:
    repo: free-pdk/easy-pdk-programmer-software
    tags: true
    all_branches: true
